apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-kubernetes
  name: nodejs-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-kubernetes
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs-kubernetes
    spec:
      containers:
        - env:
            - name: MONGO_DB_URL
              value: mongodb://nodejs-kubernetes-mongodb:27017/nodejs-kubernetes
            - name: PORT
              value: "80"
          image: nakashitanb/local-nodejs-kubernetes
          name: nodejs-kubernetes
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
