apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-kubernetes
  name: nodejs-kubernetes
spec:
  type: LoadBalancer
  ports:
    - name: "8099"
      port: 8099
      targetPort: 80
  selector:
    io.kompose.service: nodejs-kubernetes
status:
  loadBalancer: {}
